"""Telegram morning brief notifier for US Stock AI."""
from __future__ import annotations

import asyncio
import os
from datetime import date
from typing import Any

from src.config_loader import env
from src.scoring.score_engine import StockScore


def _fmt_score_line(s: StockScore) -> str:
    themes = ",".join(s.themes[:2]) if s.themes else "-"
    stop = f"${s.stop_price:.2f}" if s.stop_price else "—"
    return (
        f"*{s.symbol}* [{s.grade}] {s.total_score}pt  ${s.price:.2f}→stop {stop}\n"
        f"  {s.action} | {themes}\n"
        f"  T{s.technical_score} F{s.fundamental_score} Fl{s.flow_score} "
        f"N{s.news_catalyst_score} M{s.market_sentiment_score} -R{s.risk_penalty}"
    )


def _build_morning_report(
    top_scores: list[StockScore],
    market_prices: dict[str, float],
    today: date,
    ai_summaries: dict[str, str] | None = None,
) -> list[str]:
    """Build segmented Telegram messages (each <4000 chars)."""
    ai_summaries = ai_summaries or {}
    vix = market_prices.get("^VIX", 0)
    spy = market_prices.get("SPY", 0)
    qqq = market_prices.get("QQQ", 0)

    header = (
        f"*US Stock AI Morning Brief — {today}*\n"
        f"SPY ${spy:.2f} | QQQ ${qqq:.2f} | VIX {vix:.1f}\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    )

    grade_s = [s for s in top_scores if s.grade == "S"]
    grade_a = [s for s in top_scores if s.grade == "A"]
    others = [s for s in top_scores if s.grade not in ("S", "A")]

    parts: list[str] = []
    body = header

    def _flush_if_needed(segment: str) -> None:
        nonlocal body
        if len(body) + len(segment) > 3800:
            parts.append(body)
            body = ""
        body += segment

    if grade_s:
        _flush_if_needed("🚀 *Grade S — Strong Buy Candidates*\n")
        for s in grade_s:
            _flush_if_needed(_fmt_score_line(s) + "\n")
            if s.symbol in ai_summaries:
                _flush_if_needed(f"  _AI: {ai_summaries[s.symbol]}_\n")
            _flush_if_needed("\n")

    if grade_a:
        _flush_if_needed("📈 *Grade A — Watch / Buy Pullback*\n")
        for s in grade_a:
            _flush_if_needed(_fmt_score_line(s) + "\n\n")

    if others:
        _flush_if_needed("📋 *Others (B/C grade) top movers*\n")
        for s in others[:5]:
            _flush_if_needed(
                f"{s.symbol} [{s.grade}] {s.total_score}pt ${s.price:.2f}\n"
            )

    body += "\n_Generated by US Stock AI_"
    parts.append(body)
    return parts


class TelegramNotifier:
    def __init__(self) -> None:
        self.token = env("TELEGRAM_BOT_TOKEN", "").strip()
        self.chat_id = env("TELEGRAM_CHAT_ID", "").strip()

    def _is_configured(self) -> bool:
        return bool(self.token and self.chat_id)

    async def _send_async(self, text: str) -> bool:
        if not self._is_configured():
            print("[Telegram] Not configured — skipping send")
            return False
        try:
            from telegram import Bot
            from telegram.constants import ParseMode

            bot = Bot(token=self.token)
            await bot.send_message(
                chat_id=self.chat_id,
                text=text,
                parse_mode=ParseMode.MARKDOWN,
                disable_web_page_preview=True,
            )
            return True
        except Exception as exc:
            print(f"[Telegram] Send failed: {exc}")
            return False

    def send(self, text: str) -> bool:
        return asyncio.run(self._send_async(text))

    def send_morning_report(
        self,
        top_scores: list[StockScore],
        market_prices: dict[str, float],
        today: date | None = None,
        ai_summaries: dict[str, str] | None = None,
    ) -> bool:
        today = today or date.today()
        segments = _build_morning_report(top_scores, market_prices, today, ai_summaries)
        ok = True
        for seg in segments:
            if not self.send(seg):
                ok = False
        return ok
